### PR TITLE
docs: Add a default code of conduct

### LINKED ISSUE #7: CONTRIBUTING.md
Create a standard Contributing.md file to be added to each repo

### PR DESCRIPTION
**Pull request by timoguin**
## Added

- Adds the Contributor Covenant as the default Code of Conduct

Closes #7

### CODE REVIEW

**Comment by timoguin** [comment]
@mike-audi this is ready to look at. We just need an email contact to replace the "contact method" placeholder in the text. Let me know which one to use, and I'll mark this PR as ready.

**Review by mike-audi — APPROVED** [review]

**Comment by mike-audi** [comment]
Email conduct at mytiki.com is set up. Approved and ready to merge upon addition of the email.

**Comment by timoguin** [comment]
Updated. I just went ahead and made it into a mailto link as well. Should do the same for the security policy email.

**Comment by timoguin** [comment]
This closes #9. I tagged the wrong issue in my original PR.

**Pull request merged**
